Repository reisbalans/nextrelease-test, pull requests merged in 2020-04, with the labels that each got.

#20 Bump fake dependency
  package.json
Labels: dependency

#22 Patch fake dependency
  package.json
Labels: dependency

#23 Fix spelling in template
  .github/release-drafter.yml
Labels: bug

#31 Explicitly define source branch
  .github/workflows/release-master-pr.yml
  package.json
Labels: bug

#47 Fix syntax
  .github/workflows/release-master-pr.yml
  package.json
Labels: bug

#71 new feature
  newAwesomeFeature.md
Labels: feature

#77 Generate unique release branches
  .github/workflows/release-master-pr.yml
  README.md
Labels: bug
